
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: devtroncd
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: microk8s-hostpath
  volumeMode: Filesystem
